'use strict';
let session, selectedTest='A', selectedVariant='original', sequence=0;
const voices={}, pending=new Map();
const $=id=>document.getElementById(id);
const dimensions=[['pronunciation','Telaffuz'],['naturalness','Doğallık'],['intonation','Tonlama'],['overall','Genel beğeni']];
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
async function request(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;}
function status(text,error=false){$('save-status').textContent=text;$('save-status').classList.toggle('error',error);}
function updateProgress(){ $('progress').textContent=`${session.rated} / ${session.required}`;$('reveal').disabled=!session.complete||session.revealed;$('reveal').textContent=session.revealed?'İsimler açıldı · seçim sende':'Testi tamamla · isimleri göster';}
async function save(id){const entry=session.ratings[id];if(!entry)return;try{const result=await request('/api/save',{id,ratings:entry.scores,comment:entry.comment||''});session.rated=result.rated;session.complete=result.complete;updateProgress();status('Kaydedildi · tts/comparison/results/ altında yerel JSON');}catch(error){status(`Kayıt başarısız: ${error.message}`,true);}}
function stopAll(){sequence++;document.querySelectorAll('audio').forEach(audio=>audio.pause());$('play-all').disabled=false;}
function clipFor(group){return group.clips.find(c=>c.test===selectedTest&&c.variant===selectedVariant&&c.voice===(voices[group.alias]||'0'));}
function renderCards(){stopAll();$('cards').replaceChildren();session.groups.forEach(group=>{const clip=clipFor(group);const card=el('article',undefined,'card');const head=el('div',undefined,'card-head');const title=el('h2',group.alias);if(group.name)title.append(el('span',group.name,'revealed-name'));head.append(title,el('span',`${clip.duration.toFixed(1).replace('.',',')} sn`,'duration'));card.append(head);const label=el('label','Ses profili');const select=el('select');select.setAttribute('aria-label',`${group.alias} ses profili`);group.voices.forEach(voice=>{const option=el('option',voice.label);option.value=voice.id;select.append(option);});select.value=voices[group.alias]||'0';select.addEventListener('change',()=>{voices[group.alias]=select.value;renderCards();});label.append(select);card.append(label);const audio=el('audio');audio.controls=true;audio.preload='none';audio.src=`/audio/${clip.id}`;audio.setAttribute('aria-label',`${group.alias} dinle`);audio.addEventListener('play',()=>{document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause();});title.classList.add('playing');});audio.addEventListener('pause',()=>title.classList.remove('playing'));audio.addEventListener('ended',()=>title.classList.remove('playing'));card.append(audio);
const rating=session.ratings[clip.id]||{scores:{},comment:''};session.ratings[clip.id]=rating;dimensions.forEach(([key,name])=>{const row=el('div',undefined,'rating');const field=el('fieldset');field.setAttribute('aria-label',`${group.alias} ${name}`);row.append(el('span',name));for(let value=1;value<=5;value++){const b=el('button',String(value),'score');b.type='button';b.setAttribute('aria-label',`${name}: ${value}`);b.setAttribute('aria-pressed',String(rating.scores[key]===value));b.addEventListener('click',()=>{rating.scores[key]=value;field.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));void save(clip.id);});field.append(b);}row.append(field);card.append(row);});card.append(el('p','1 · zayıf / 5 · çok iyi','scale'));const notes=el('label','Dinleme notların','notes');const textarea=el('textarea');textarea.value=rating.comment;textarea.maxLength=5000;textarea.placeholder='Vurgu, duraksama, yanlış okunan sözcük…';textarea.addEventListener('input',()=>{rating.comment=textarea.value;clearTimeout(pending.get(clip.id));pending.set(clip.id,setTimeout(()=>void save(clip.id),500));});notes.append(textarea);card.append(notes);$('cards').append(card);});}
function render(){const test=session.tests.find(t=>t.id===selectedTest);$('test-title').textContent=`TEST ${test.id} / ${test.title}`;$('text').textContent=selectedVariant==='normalized'?test.normalized:test.text;$('word-count').textContent=`${$('text').textContent.split(/\s+/).length} kelime`;$('variant').querySelector('[value="normalized"]').disabled=!test.normalized;$('variant').querySelector('[value="duration-42"]').disabled=test.id!=='D';$('variant').value=selectedVariant;$('context').textContent=selectedVariant==='duration-42'?'İkinci hız testi: aynı metin, modelin kendi sentez hızıyla yaklaşık 42 saniye. Doğal hız orijinalde saklı.':selectedVariant==='normalized'?'Aynı sayılar yazıyla verildi. Bu bir telaffuz tanısıdır; orijinal çıktı ayrı tutulur.': 'Her modelin önerilen doğal hız ayarı. Konuşma hızları ve ses uzunlukları bu yüzden farklı olabilir.';document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.id===selectedTest)));renderCards();updateProgress();}
$('variant').addEventListener('change',()=>{selectedVariant=$('variant').value;render();});$('stop').addEventListener('click',stopAll);
$('play-all').addEventListener('click',async()=>{stopAll();const token=sequence;$('play-all').disabled=true;for(const audio of document.querySelectorAll('audio')){if(token!==sequence)break;audio.currentTime=0;try{await audio.play();await new Promise(resolve=>{audio.addEventListener('ended',resolve,{once:true});audio.addEventListener('pause',resolve,{once:true});audio.addEventListener('error',resolve,{once:true});});}catch(error){status(`Oynatma sorunu: ${error.message}`,true);break;}}$('play-all').disabled=false;});
$('reveal').addEventListener('click',async()=>{try{session=await request('/api/save',{reveal:true});render();status('Model isimleri açıldı. Otomatik sıralama yapılmadı; değerlendirme sana ait.');}catch(error){status(error.message,true);}});
request('/api/session').then(data=>{session=data;session.tests.forEach(test=>{const button=el('button');button.dataset.id=test.id;button.append(el('b',test.id),document.createTextNode(test.title.split(' · ')[0]));button.addEventListener('click',()=>{selectedTest=test.id;selectedVariant='original';render();});$('tests').append(button);});render();}).catch(error=>status(`Başlatılamadı: ${error.message}`,true));
